export const products = [
    {id:1, 
    name:"Comelento Trixie", 
    category:"Toy",
    description:"Description", 
    stock:10, 
    price:6200, 
    image:"../images/comelento-trixie.jpg"},

    {id:2, 
    name:"Disco común Disc Dog",
    category:"Toy",
    description:"Description", 
    stock:9, 
    price: 1300, 
    image:"../images/disc-dog.jpg"},

    {id:3, 
    name:"Hueso KONG Classic Grande", 
    category:"Toy",
    description:"Description", 
    stock:8, 
    price: 8600, 
    image:"../images/hueso-classic.jpg"},

    {id:4, 
    name:"Juego Trixie Torre",
    category:"Toy",
    description:"Description", 
    stock:7, 
    price: 9600, 
    image:"../images/juego-torre-trixie.jpg"},

    {id:5, 
    name:"KONG Classic", 
    category:"Toy",
    description:"Description", 
    stock:10, 
    price:4200, 
    image:"../images/kong-classic.jpg"},

    {id:6, 
    name:"LickiMat Tuff Buddy", 
    category:"Toy",
    description:"Description", 
    stock:9, 
    price: 7500, 
    image:"../images/lickiMAt-tuff-buddy.jpg"},

    {id:7, 
    name:"Pelota KONG con soga y chifle", 
    category:"Toy",
    description:"Description", 
    stock:8, 
    price: 2700, 
    image:"../images/pelota-soga.jpg"},

    {id:8, 
    name:"Soga de Algodón", 
    category:"Toy",
    description:"Description", 
    stock:7, 
    price: 800, 
    image:"../images/soga-algodon.jpg"},

    {id:9, 
    name:"KONG Extreme", 
    category:"Toy",
    description:"Description", 
    stock:7, 
    price: 4500, 
    image:"../images/kong-extreme.jpg"}
];